#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Hangman.Resource", IsApplication=true)]

namespace Hangman
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Xamarin.Essentials.Resource.Attribute.alpha = global::Hangman.Resource.Attribute.alpha;
			global::Xamarin.Essentials.Resource.Attribute.coordinatorLayoutStyle = global::Hangman.Resource.Attribute.coordinatorLayoutStyle;
			global::Xamarin.Essentials.Resource.Attribute.font = global::Hangman.Resource.Attribute.font;
			global::Xamarin.Essentials.Resource.Attribute.fontProviderAuthority = global::Hangman.Resource.Attribute.fontProviderAuthority;
			global::Xamarin.Essentials.Resource.Attribute.fontProviderCerts = global::Hangman.Resource.Attribute.fontProviderCerts;
			global::Xamarin.Essentials.Resource.Attribute.fontProviderFetchStrategy = global::Hangman.Resource.Attribute.fontProviderFetchStrategy;
			global::Xamarin.Essentials.Resource.Attribute.fontProviderFetchTimeout = global::Hangman.Resource.Attribute.fontProviderFetchTimeout;
			global::Xamarin.Essentials.Resource.Attribute.fontProviderPackage = global::Hangman.Resource.Attribute.fontProviderPackage;
			global::Xamarin.Essentials.Resource.Attribute.fontProviderQuery = global::Hangman.Resource.Attribute.fontProviderQuery;
			global::Xamarin.Essentials.Resource.Attribute.fontStyle = global::Hangman.Resource.Attribute.fontStyle;
			global::Xamarin.Essentials.Resource.Attribute.fontVariationSettings = global::Hangman.Resource.Attribute.fontVariationSettings;
			global::Xamarin.Essentials.Resource.Attribute.fontWeight = global::Hangman.Resource.Attribute.fontWeight;
			global::Xamarin.Essentials.Resource.Attribute.keylines = global::Hangman.Resource.Attribute.keylines;
			global::Xamarin.Essentials.Resource.Attribute.layout_anchor = global::Hangman.Resource.Attribute.layout_anchor;
			global::Xamarin.Essentials.Resource.Attribute.layout_anchorGravity = global::Hangman.Resource.Attribute.layout_anchorGravity;
			global::Xamarin.Essentials.Resource.Attribute.layout_behavior = global::Hangman.Resource.Attribute.layout_behavior;
			global::Xamarin.Essentials.Resource.Attribute.layout_dodgeInsetEdges = global::Hangman.Resource.Attribute.layout_dodgeInsetEdges;
			global::Xamarin.Essentials.Resource.Attribute.layout_insetEdge = global::Hangman.Resource.Attribute.layout_insetEdge;
			global::Xamarin.Essentials.Resource.Attribute.layout_keyline = global::Hangman.Resource.Attribute.layout_keyline;
			global::Xamarin.Essentials.Resource.Attribute.statusBarBackground = global::Hangman.Resource.Attribute.statusBarBackground;
			global::Xamarin.Essentials.Resource.Attribute.ttcIndex = global::Hangman.Resource.Attribute.ttcIndex;
			global::Xamarin.Essentials.Resource.Color.browser_actions_bg_grey = global::Hangman.Resource.Color.browser_actions_bg_grey;
			global::Xamarin.Essentials.Resource.Color.browser_actions_divider_color = global::Hangman.Resource.Color.browser_actions_divider_color;
			global::Xamarin.Essentials.Resource.Color.browser_actions_text_color = global::Hangman.Resource.Color.browser_actions_text_color;
			global::Xamarin.Essentials.Resource.Color.browser_actions_title_color = global::Hangman.Resource.Color.browser_actions_title_color;
			global::Xamarin.Essentials.Resource.Color.notification_action_color_filter = global::Hangman.Resource.Color.notification_action_color_filter;
			global::Xamarin.Essentials.Resource.Color.notification_icon_bg_color = global::Hangman.Resource.Color.notification_icon_bg_color;
			global::Xamarin.Essentials.Resource.Color.ripple_material_light = global::Hangman.Resource.Color.ripple_material_light;
			global::Xamarin.Essentials.Resource.Color.secondary_text_default_material_light = global::Hangman.Resource.Color.secondary_text_default_material_light;
			global::Xamarin.Essentials.Resource.Dimension.browser_actions_context_menu_max_width = global::Hangman.Resource.Dimension.browser_actions_context_menu_max_width;
			global::Xamarin.Essentials.Resource.Dimension.browser_actions_context_menu_min_padding = global::Hangman.Resource.Dimension.browser_actions_context_menu_min_padding;
			global::Xamarin.Essentials.Resource.Dimension.compat_button_inset_horizontal_material = global::Hangman.Resource.Dimension.compat_button_inset_horizontal_material;
			global::Xamarin.Essentials.Resource.Dimension.compat_button_inset_vertical_material = global::Hangman.Resource.Dimension.compat_button_inset_vertical_material;
			global::Xamarin.Essentials.Resource.Dimension.compat_button_padding_horizontal_material = global::Hangman.Resource.Dimension.compat_button_padding_horizontal_material;
			global::Xamarin.Essentials.Resource.Dimension.compat_button_padding_vertical_material = global::Hangman.Resource.Dimension.compat_button_padding_vertical_material;
			global::Xamarin.Essentials.Resource.Dimension.compat_control_corner_material = global::Hangman.Resource.Dimension.compat_control_corner_material;
			global::Xamarin.Essentials.Resource.Dimension.compat_notification_large_icon_max_height = global::Hangman.Resource.Dimension.compat_notification_large_icon_max_height;
			global::Xamarin.Essentials.Resource.Dimension.compat_notification_large_icon_max_width = global::Hangman.Resource.Dimension.compat_notification_large_icon_max_width;
			global::Xamarin.Essentials.Resource.Dimension.notification_action_icon_size = global::Hangman.Resource.Dimension.notification_action_icon_size;
			global::Xamarin.Essentials.Resource.Dimension.notification_action_text_size = global::Hangman.Resource.Dimension.notification_action_text_size;
			global::Xamarin.Essentials.Resource.Dimension.notification_big_circle_margin = global::Hangman.Resource.Dimension.notification_big_circle_margin;
			global::Xamarin.Essentials.Resource.Dimension.notification_content_margin_start = global::Hangman.Resource.Dimension.notification_content_margin_start;
			global::Xamarin.Essentials.Resource.Dimension.notification_large_icon_height = global::Hangman.Resource.Dimension.notification_large_icon_height;
			global::Xamarin.Essentials.Resource.Dimension.notification_large_icon_width = global::Hangman.Resource.Dimension.notification_large_icon_width;
			global::Xamarin.Essentials.Resource.Dimension.notification_main_column_padding_top = global::Hangman.Resource.Dimension.notification_main_column_padding_top;
			global::Xamarin.Essentials.Resource.Dimension.notification_media_narrow_margin = global::Hangman.Resource.Dimension.notification_media_narrow_margin;
			global::Xamarin.Essentials.Resource.Dimension.notification_right_icon_size = global::Hangman.Resource.Dimension.notification_right_icon_size;
			global::Xamarin.Essentials.Resource.Dimension.notification_right_side_padding_top = global::Hangman.Resource.Dimension.notification_right_side_padding_top;
			global::Xamarin.Essentials.Resource.Dimension.notification_small_icon_background_padding = global::Hangman.Resource.Dimension.notification_small_icon_background_padding;
			global::Xamarin.Essentials.Resource.Dimension.notification_small_icon_size_as_large = global::Hangman.Resource.Dimension.notification_small_icon_size_as_large;
			global::Xamarin.Essentials.Resource.Dimension.notification_subtext_size = global::Hangman.Resource.Dimension.notification_subtext_size;
			global::Xamarin.Essentials.Resource.Dimension.notification_top_pad = global::Hangman.Resource.Dimension.notification_top_pad;
			global::Xamarin.Essentials.Resource.Dimension.notification_top_pad_large_text = global::Hangman.Resource.Dimension.notification_top_pad_large_text;
			global::Xamarin.Essentials.Resource.Drawable.notification_action_background = global::Hangman.Resource.Drawable.notification_action_background;
			global::Xamarin.Essentials.Resource.Drawable.notification_bg = global::Hangman.Resource.Drawable.notification_bg;
			global::Xamarin.Essentials.Resource.Drawable.notification_bg_low = global::Hangman.Resource.Drawable.notification_bg_low;
			global::Xamarin.Essentials.Resource.Drawable.notification_bg_low_normal = global::Hangman.Resource.Drawable.notification_bg_low_normal;
			global::Xamarin.Essentials.Resource.Drawable.notification_bg_low_pressed = global::Hangman.Resource.Drawable.notification_bg_low_pressed;
			global::Xamarin.Essentials.Resource.Drawable.notification_bg_normal = global::Hangman.Resource.Drawable.notification_bg_normal;
			global::Xamarin.Essentials.Resource.Drawable.notification_bg_normal_pressed = global::Hangman.Resource.Drawable.notification_bg_normal_pressed;
			global::Xamarin.Essentials.Resource.Drawable.notification_icon_background = global::Hangman.Resource.Drawable.notification_icon_background;
			global::Xamarin.Essentials.Resource.Drawable.notification_template_icon_bg = global::Hangman.Resource.Drawable.notification_template_icon_bg;
			global::Xamarin.Essentials.Resource.Drawable.notification_template_icon_low_bg = global::Hangman.Resource.Drawable.notification_template_icon_low_bg;
			global::Xamarin.Essentials.Resource.Drawable.notification_tile_bg = global::Hangman.Resource.Drawable.notification_tile_bg;
			global::Xamarin.Essentials.Resource.Drawable.notify_panel_notification_icon_bg = global::Hangman.Resource.Drawable.notify_panel_notification_icon_bg;
			global::Xamarin.Essentials.Resource.Id.action_container = global::Hangman.Resource.Id.action_container;
			global::Xamarin.Essentials.Resource.Id.action_divider = global::Hangman.Resource.Id.action_divider;
			global::Xamarin.Essentials.Resource.Id.action_image = global::Hangman.Resource.Id.action_image;
			global::Xamarin.Essentials.Resource.Id.action_text = global::Hangman.Resource.Id.action_text;
			global::Xamarin.Essentials.Resource.Id.actions = global::Hangman.Resource.Id.actions;
			global::Xamarin.Essentials.Resource.Id.all = global::Hangman.Resource.Id.all;
			global::Xamarin.Essentials.Resource.Id.async = global::Hangman.Resource.Id.async;
			global::Xamarin.Essentials.Resource.Id.blocking = global::Hangman.Resource.Id.blocking;
			global::Xamarin.Essentials.Resource.Id.bottom = global::Hangman.Resource.Id.bottom;
			global::Xamarin.Essentials.Resource.Id.browser_actions_header_text = global::Hangman.Resource.Id.browser_actions_header_text;
			global::Xamarin.Essentials.Resource.Id.browser_actions_menu_item_icon = global::Hangman.Resource.Id.browser_actions_menu_item_icon;
			global::Xamarin.Essentials.Resource.Id.browser_actions_menu_item_text = global::Hangman.Resource.Id.browser_actions_menu_item_text;
			global::Xamarin.Essentials.Resource.Id.browser_actions_menu_items = global::Hangman.Resource.Id.browser_actions_menu_items;
			global::Xamarin.Essentials.Resource.Id.browser_actions_menu_view = global::Hangman.Resource.Id.browser_actions_menu_view;
			global::Xamarin.Essentials.Resource.Id.center = global::Hangman.Resource.Id.center;
			global::Xamarin.Essentials.Resource.Id.center_horizontal = global::Hangman.Resource.Id.center_horizontal;
			global::Xamarin.Essentials.Resource.Id.center_vertical = global::Hangman.Resource.Id.center_vertical;
			global::Xamarin.Essentials.Resource.Id.chronometer = global::Hangman.Resource.Id.chronometer;
			global::Xamarin.Essentials.Resource.Id.clip_horizontal = global::Hangman.Resource.Id.clip_horizontal;
			global::Xamarin.Essentials.Resource.Id.clip_vertical = global::Hangman.Resource.Id.clip_vertical;
			global::Xamarin.Essentials.Resource.Id.end = global::Hangman.Resource.Id.end;
			global::Xamarin.Essentials.Resource.Id.fill = global::Hangman.Resource.Id.fill;
			global::Xamarin.Essentials.Resource.Id.fill_horizontal = global::Hangman.Resource.Id.fill_horizontal;
			global::Xamarin.Essentials.Resource.Id.fill_vertical = global::Hangman.Resource.Id.fill_vertical;
			global::Xamarin.Essentials.Resource.Id.forever = global::Hangman.Resource.Id.forever;
			global::Xamarin.Essentials.Resource.Id.icon = global::Hangman.Resource.Id.icon;
			global::Xamarin.Essentials.Resource.Id.icon_group = global::Hangman.Resource.Id.icon_group;
			global::Xamarin.Essentials.Resource.Id.info = global::Hangman.Resource.Id.info;
			global::Xamarin.Essentials.Resource.Id.italic = global::Hangman.Resource.Id.italic;
			global::Xamarin.Essentials.Resource.Id.left = global::Hangman.Resource.Id.left;
			global::Xamarin.Essentials.Resource.Id.line1 = global::Hangman.Resource.Id.line1;
			global::Xamarin.Essentials.Resource.Id.line3 = global::Hangman.Resource.Id.line3;
			global::Xamarin.Essentials.Resource.Id.none = global::Hangman.Resource.Id.none;
			global::Xamarin.Essentials.Resource.Id.normal = global::Hangman.Resource.Id.normal;
			global::Xamarin.Essentials.Resource.Id.notification_background = global::Hangman.Resource.Id.notification_background;
			global::Xamarin.Essentials.Resource.Id.notification_main_column = global::Hangman.Resource.Id.notification_main_column;
			global::Xamarin.Essentials.Resource.Id.notification_main_column_container = global::Hangman.Resource.Id.notification_main_column_container;
			global::Xamarin.Essentials.Resource.Id.right = global::Hangman.Resource.Id.right;
			global::Xamarin.Essentials.Resource.Id.right_icon = global::Hangman.Resource.Id.right_icon;
			global::Xamarin.Essentials.Resource.Id.right_side = global::Hangman.Resource.Id.right_side;
			global::Xamarin.Essentials.Resource.Id.start = global::Hangman.Resource.Id.start;
			global::Xamarin.Essentials.Resource.Id.tag_transition_group = global::Hangman.Resource.Id.tag_transition_group;
			global::Xamarin.Essentials.Resource.Id.tag_unhandled_key_event_manager = global::Hangman.Resource.Id.tag_unhandled_key_event_manager;
			global::Xamarin.Essentials.Resource.Id.tag_unhandled_key_listeners = global::Hangman.Resource.Id.tag_unhandled_key_listeners;
			global::Xamarin.Essentials.Resource.Id.text = global::Hangman.Resource.Id.text;
			global::Xamarin.Essentials.Resource.Id.text2 = global::Hangman.Resource.Id.text2;
			global::Xamarin.Essentials.Resource.Id.time = global::Hangman.Resource.Id.time;
			global::Xamarin.Essentials.Resource.Id.title = global::Hangman.Resource.Id.title;
			global::Xamarin.Essentials.Resource.Id.top = global::Hangman.Resource.Id.top;
			global::Xamarin.Essentials.Resource.Integer.status_bar_notification_info_maxnum = global::Hangman.Resource.Integer.status_bar_notification_info_maxnum;
			global::Xamarin.Essentials.Resource.Layout.browser_actions_context_menu_page = global::Hangman.Resource.Layout.browser_actions_context_menu_page;
			global::Xamarin.Essentials.Resource.Layout.browser_actions_context_menu_row = global::Hangman.Resource.Layout.browser_actions_context_menu_row;
			global::Xamarin.Essentials.Resource.Layout.notification_action = global::Hangman.Resource.Layout.notification_action;
			global::Xamarin.Essentials.Resource.Layout.notification_action_tombstone = global::Hangman.Resource.Layout.notification_action_tombstone;
			global::Xamarin.Essentials.Resource.Layout.notification_template_custom_big = global::Hangman.Resource.Layout.notification_template_custom_big;
			global::Xamarin.Essentials.Resource.Layout.notification_template_icon_group = global::Hangman.Resource.Layout.notification_template_icon_group;
			global::Xamarin.Essentials.Resource.Layout.notification_template_part_chronometer = global::Hangman.Resource.Layout.notification_template_part_chronometer;
			global::Xamarin.Essentials.Resource.Layout.notification_template_part_time = global::Hangman.Resource.Layout.notification_template_part_time;
			global::Xamarin.Essentials.Resource.String.status_bar_notification_info_overflow = global::Hangman.Resource.String.status_bar_notification_info_overflow;
			global::Xamarin.Essentials.Resource.Style.TextAppearance_Compat_Notification = global::Hangman.Resource.Style.TextAppearance_Compat_Notification;
			global::Xamarin.Essentials.Resource.Style.TextAppearance_Compat_Notification_Info = global::Hangman.Resource.Style.TextAppearance_Compat_Notification_Info;
			global::Xamarin.Essentials.Resource.Style.TextAppearance_Compat_Notification_Line2 = global::Hangman.Resource.Style.TextAppearance_Compat_Notification_Line2;
			global::Xamarin.Essentials.Resource.Style.TextAppearance_Compat_Notification_Time = global::Hangman.Resource.Style.TextAppearance_Compat_Notification_Time;
			global::Xamarin.Essentials.Resource.Style.TextAppearance_Compat_Notification_Title = global::Hangman.Resource.Style.TextAppearance_Compat_Notification_Title;
			global::Xamarin.Essentials.Resource.Style.Widget_Compat_NotificationActionContainer = global::Hangman.Resource.Style.Widget_Compat_NotificationActionContainer;
			global::Xamarin.Essentials.Resource.Style.Widget_Compat_NotificationActionText = global::Hangman.Resource.Style.Widget_Compat_NotificationActionText;
			global::Xamarin.Essentials.Resource.Style.Widget_Support_CoordinatorLayout = global::Hangman.Resource.Style.Widget_Support_CoordinatorLayout;
			global::Xamarin.Essentials.Resource.Xml.xamarin_essentials_fileprovider_file_paths = global::Hangman.Resource.Xml.xamarin_essentials_fileprovider_file_paths;
			global::Xamarin.Essentials.Resource.Styleable.ColorStateListItem = global::Hangman.Resource.Styleable.ColorStateListItem;
			global::Xamarin.Essentials.Resource.Styleable.ColorStateListItem_alpha = global::Hangman.Resource.Styleable.ColorStateListItem_alpha;
			global::Xamarin.Essentials.Resource.Styleable.ColorStateListItem_android_alpha = global::Hangman.Resource.Styleable.ColorStateListItem_android_alpha;
			global::Xamarin.Essentials.Resource.Styleable.ColorStateListItem_android_color = global::Hangman.Resource.Styleable.ColorStateListItem_android_color;
			global::Xamarin.Essentials.Resource.Styleable.CoordinatorLayout = global::Hangman.Resource.Styleable.CoordinatorLayout;
			global::Xamarin.Essentials.Resource.Styleable.CoordinatorLayout_keylines = global::Hangman.Resource.Styleable.CoordinatorLayout_keylines;
			global::Xamarin.Essentials.Resource.Styleable.CoordinatorLayout_statusBarBackground = global::Hangman.Resource.Styleable.CoordinatorLayout_statusBarBackground;
			global::Xamarin.Essentials.Resource.Styleable.CoordinatorLayout_Layout = global::Hangman.Resource.Styleable.CoordinatorLayout_Layout;
			global::Xamarin.Essentials.Resource.Styleable.CoordinatorLayout_Layout_android_layout_gravity = global::Hangman.Resource.Styleable.CoordinatorLayout_Layout_android_layout_gravity;
			global::Xamarin.Essentials.Resource.Styleable.CoordinatorLayout_Layout_layout_anchor = global::Hangman.Resource.Styleable.CoordinatorLayout_Layout_layout_anchor;
			global::Xamarin.Essentials.Resource.Styleable.CoordinatorLayout_Layout_layout_anchorGravity = global::Hangman.Resource.Styleable.CoordinatorLayout_Layout_layout_anchorGravity;
			global::Xamarin.Essentials.Resource.Styleable.CoordinatorLayout_Layout_layout_behavior = global::Hangman.Resource.Styleable.CoordinatorLayout_Layout_layout_behavior;
			global::Xamarin.Essentials.Resource.Styleable.CoordinatorLayout_Layout_layout_dodgeInsetEdges = global::Hangman.Resource.Styleable.CoordinatorLayout_Layout_layout_dodgeInsetEdges;
			global::Xamarin.Essentials.Resource.Styleable.CoordinatorLayout_Layout_layout_insetEdge = global::Hangman.Resource.Styleable.CoordinatorLayout_Layout_layout_insetEdge;
			global::Xamarin.Essentials.Resource.Styleable.CoordinatorLayout_Layout_layout_keyline = global::Hangman.Resource.Styleable.CoordinatorLayout_Layout_layout_keyline;
			global::Xamarin.Essentials.Resource.Styleable.FontFamily = global::Hangman.Resource.Styleable.FontFamily;
			global::Xamarin.Essentials.Resource.Styleable.FontFamily_fontProviderAuthority = global::Hangman.Resource.Styleable.FontFamily_fontProviderAuthority;
			global::Xamarin.Essentials.Resource.Styleable.FontFamily_fontProviderCerts = global::Hangman.Resource.Styleable.FontFamily_fontProviderCerts;
			global::Xamarin.Essentials.Resource.Styleable.FontFamily_fontProviderFetchStrategy = global::Hangman.Resource.Styleable.FontFamily_fontProviderFetchStrategy;
			global::Xamarin.Essentials.Resource.Styleable.FontFamily_fontProviderFetchTimeout = global::Hangman.Resource.Styleable.FontFamily_fontProviderFetchTimeout;
			global::Xamarin.Essentials.Resource.Styleable.FontFamily_fontProviderPackage = global::Hangman.Resource.Styleable.FontFamily_fontProviderPackage;
			global::Xamarin.Essentials.Resource.Styleable.FontFamily_fontProviderQuery = global::Hangman.Resource.Styleable.FontFamily_fontProviderQuery;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont = global::Hangman.Resource.Styleable.FontFamilyFont;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont_android_font = global::Hangman.Resource.Styleable.FontFamilyFont_android_font;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont_android_fontStyle = global::Hangman.Resource.Styleable.FontFamilyFont_android_fontStyle;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont_android_fontVariationSettings = global::Hangman.Resource.Styleable.FontFamilyFont_android_fontVariationSettings;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont_android_fontWeight = global::Hangman.Resource.Styleable.FontFamilyFont_android_fontWeight;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont_android_ttcIndex = global::Hangman.Resource.Styleable.FontFamilyFont_android_ttcIndex;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont_font = global::Hangman.Resource.Styleable.FontFamilyFont_font;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont_fontStyle = global::Hangman.Resource.Styleable.FontFamilyFont_fontStyle;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont_fontVariationSettings = global::Hangman.Resource.Styleable.FontFamilyFont_fontVariationSettings;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont_fontWeight = global::Hangman.Resource.Styleable.FontFamilyFont_fontWeight;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont_ttcIndex = global::Hangman.Resource.Styleable.FontFamilyFont_ttcIndex;
			global::Xamarin.Essentials.Resource.Styleable.GradientColor = global::Hangman.Resource.Styleable.GradientColor;
			global::Xamarin.Essentials.Resource.Styleable.GradientColor_android_centerColor = global::Hangman.Resource.Styleable.GradientColor_android_centerColor;
			global::Xamarin.Essentials.Resource.Styleable.GradientColor_android_centerX = global::Hangman.Resource.Styleable.GradientColor_android_centerX;
			global::Xamarin.Essentials.Resource.Styleable.GradientColor_android_centerY = global::Hangman.Resource.Styleable.GradientColor_android_centerY;
			global::Xamarin.Essentials.Resource.Styleable.GradientColor_android_endColor = global::Hangman.Resource.Styleable.GradientColor_android_endColor;
			global::Xamarin.Essentials.Resource.Styleable.GradientColor_android_endX = global::Hangman.Resource.Styleable.GradientColor_android_endX;
			global::Xamarin.Essentials.Resource.Styleable.GradientColor_android_endY = global::Hangman.Resource.Styleable.GradientColor_android_endY;
			global::Xamarin.Essentials.Resource.Styleable.GradientColor_android_gradientRadius = global::Hangman.Resource.Styleable.GradientColor_android_gradientRadius;
			global::Xamarin.Essentials.Resource.Styleable.GradientColor_android_startColor = global::Hangman.Resource.Styleable.GradientColor_android_startColor;
			global::Xamarin.Essentials.Resource.Styleable.GradientColor_android_startX = global::Hangman.Resource.Styleable.GradientColor_android_startX;
			global::Xamarin.Essentials.Resource.Styleable.GradientColor_android_startY = global::Hangman.Resource.Styleable.GradientColor_android_startY;
			global::Xamarin.Essentials.Resource.Styleable.GradientColor_android_tileMode = global::Hangman.Resource.Styleable.GradientColor_android_tileMode;
			global::Xamarin.Essentials.Resource.Styleable.GradientColor_android_type = global::Hangman.Resource.Styleable.GradientColor_android_type;
			global::Xamarin.Essentials.Resource.Styleable.GradientColorItem = global::Hangman.Resource.Styleable.GradientColorItem;
			global::Xamarin.Essentials.Resource.Styleable.GradientColorItem_android_color = global::Hangman.Resource.Styleable.GradientColorItem_android_color;
			global::Xamarin.Essentials.Resource.Styleable.GradientColorItem_android_offset = global::Hangman.Resource.Styleable.GradientColorItem_android_offset;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7F010000
			public const int difficulty_array = 2130771968;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7F020000
			public const int alpha = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int coordinatorLayoutStyle = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int font = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int fontProviderAuthority = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int fontProviderCerts = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int fontProviderFetchStrategy = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int fontProviderFetchTimeout = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int fontProviderPackage = 2130837511;
			
			// aapt resource value: 0x7F020008
			public const int fontProviderQuery = 2130837512;
			
			// aapt resource value: 0x7F020009
			public const int fontStyle = 2130837513;
			
			// aapt resource value: 0x7F02000A
			public const int fontVariationSettings = 2130837514;
			
			// aapt resource value: 0x7F02000B
			public const int fontWeight = 2130837515;
			
			// aapt resource value: 0x7F02000C
			public const int keylines = 2130837516;
			
			// aapt resource value: 0x7F02000D
			public const int layout_anchor = 2130837517;
			
			// aapt resource value: 0x7F02000E
			public const int layout_anchorGravity = 2130837518;
			
			// aapt resource value: 0x7F02000F
			public const int layout_behavior = 2130837519;
			
			// aapt resource value: 0x7F020010
			public const int layout_dodgeInsetEdges = 2130837520;
			
			// aapt resource value: 0x7F020011
			public const int layout_insetEdge = 2130837521;
			
			// aapt resource value: 0x7F020012
			public const int layout_keyline = 2130837522;
			
			// aapt resource value: 0x7F020013
			public const int statusBarBackground = 2130837523;
			
			// aapt resource value: 0x7F020014
			public const int ttcIndex = 2130837524;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F030000
			public const int browser_actions_bg_grey = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int browser_actions_divider_color = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int browser_actions_text_color = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int browser_actions_title_color = 2130903043;
			
			// aapt resource value: 0x7F030004
			public const int notification_action_color_filter = 2130903044;
			
			// aapt resource value: 0x7F030005
			public const int notification_icon_bg_color = 2130903045;
			
			// aapt resource value: 0x7F030006
			public const int ripple_material_light = 2130903046;
			
			// aapt resource value: 0x7F030007
			public const int secondary_text_default_material_light = 2130903047;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7F040000
			public const int browser_actions_context_menu_max_width = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int browser_actions_context_menu_min_padding = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int compat_button_inset_horizontal_material = 2130968578;
			
			// aapt resource value: 0x7F040003
			public const int compat_button_inset_vertical_material = 2130968579;
			
			// aapt resource value: 0x7F040004
			public const int compat_button_padding_horizontal_material = 2130968580;
			
			// aapt resource value: 0x7F040005
			public const int compat_button_padding_vertical_material = 2130968581;
			
			// aapt resource value: 0x7F040006
			public const int compat_control_corner_material = 2130968582;
			
			// aapt resource value: 0x7F040007
			public const int compat_notification_large_icon_max_height = 2130968583;
			
			// aapt resource value: 0x7F040008
			public const int compat_notification_large_icon_max_width = 2130968584;
			
			// aapt resource value: 0x7F040009
			public const int notification_action_icon_size = 2130968585;
			
			// aapt resource value: 0x7F04000A
			public const int notification_action_text_size = 2130968586;
			
			// aapt resource value: 0x7F04000B
			public const int notification_big_circle_margin = 2130968587;
			
			// aapt resource value: 0x7F04000C
			public const int notification_content_margin_start = 2130968588;
			
			// aapt resource value: 0x7F04000D
			public const int notification_large_icon_height = 2130968589;
			
			// aapt resource value: 0x7F04000E
			public const int notification_large_icon_width = 2130968590;
			
			// aapt resource value: 0x7F04000F
			public const int notification_main_column_padding_top = 2130968591;
			
			// aapt resource value: 0x7F040010
			public const int notification_media_narrow_margin = 2130968592;
			
			// aapt resource value: 0x7F040011
			public const int notification_right_icon_size = 2130968593;
			
			// aapt resource value: 0x7F040012
			public const int notification_right_side_padding_top = 2130968594;
			
			// aapt resource value: 0x7F040013
			public const int notification_small_icon_background_padding = 2130968595;
			
			// aapt resource value: 0x7F040014
			public const int notification_small_icon_size_as_large = 2130968596;
			
			// aapt resource value: 0x7F040015
			public const int notification_subtext_size = 2130968597;
			
			// aapt resource value: 0x7F040016
			public const int notification_top_pad = 2130968598;
			
			// aapt resource value: 0x7F040017
			public const int notification_top_pad_large_text = 2130968599;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F050000
			public const int ArrowRight = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int FG = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int HangmanIcon = 2131034114;
			
			// aapt resource value: 0x7F050003
			public const int HM1 = 2131034115;
			
			// aapt resource value: 0x7F050004
			public const int HM2 = 2131034116;
			
			// aapt resource value: 0x7F050005
			public const int HM3 = 2131034117;
			
			// aapt resource value: 0x7F050006
			public const int HM4 = 2131034118;
			
			// aapt resource value: 0x7F050007
			public const int HM5 = 2131034119;
			
			// aapt resource value: 0x7F050008
			public const int HM6 = 2131034120;
			
			// aapt resource value: 0x7F050009
			public const int HMCreate5 = 2131034121;
			
			// aapt resource value: 0x7F05000A
			public const int HMSetup = 2131034122;
			
			// aapt resource value: 0x7F05000B
			public const int notification_action_background = 2131034123;
			
			// aapt resource value: 0x7F05000C
			public const int notification_bg = 2131034124;
			
			// aapt resource value: 0x7F05000D
			public const int notification_bg_low = 2131034125;
			
			// aapt resource value: 0x7F05000E
			public const int notification_bg_low_normal = 2131034126;
			
			// aapt resource value: 0x7F05000F
			public const int notification_bg_low_pressed = 2131034127;
			
			// aapt resource value: 0x7F050010
			public const int notification_bg_normal = 2131034128;
			
			// aapt resource value: 0x7F050011
			public const int notification_bg_normal_pressed = 2131034129;
			
			// aapt resource value: 0x7F050012
			public const int notification_icon_background = 2131034130;
			
			// aapt resource value: 0x7F050013
			public const int notification_template_icon_bg = 2131034131;
			
			// aapt resource value: 0x7F050014
			public const int notification_template_icon_low_bg = 2131034132;
			
			// aapt resource value: 0x7F050015
			public const int notification_tile_bg = 2131034133;
			
			// aapt resource value: 0x7F050016
			public const int notify_panel_notification_icon_bg = 2131034134;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F060005
			public const int actions = 2131099653;
			
			// aapt resource value: 0x7F060001
			public const int action_container = 2131099649;
			
			// aapt resource value: 0x7F060002
			public const int action_divider = 2131099650;
			
			// aapt resource value: 0x7F060003
			public const int action_image = 2131099651;
			
			// aapt resource value: 0x7F060004
			public const int action_text = 2131099652;
			
			// aapt resource value: 0x7F060006
			public const int all = 2131099654;
			
			// aapt resource value: 0x7F060007
			public const int async = 2131099655;
			
			// aapt resource value: 0x7F060008
			public const int blocking = 2131099656;
			
			// aapt resource value: 0x7F060009
			public const int bottom = 2131099657;
			
			// aapt resource value: 0x7F06000A
			public const int browser_actions_header_text = 2131099658;
			
			// aapt resource value: 0x7F06000D
			public const int browser_actions_menu_items = 2131099661;
			
			// aapt resource value: 0x7F06000B
			public const int browser_actions_menu_item_icon = 2131099659;
			
			// aapt resource value: 0x7F06000C
			public const int browser_actions_menu_item_text = 2131099660;
			
			// aapt resource value: 0x7F06000E
			public const int browser_actions_menu_view = 2131099662;
			
			// aapt resource value: 0x7F06000F
			public const int btnA = 2131099663;
			
			// aapt resource value: 0x7F060010
			public const int btnB = 2131099664;
			
			// aapt resource value: 0x7F060011
			public const int btnC = 2131099665;
			
			// aapt resource value: 0x7F060012
			public const int btnD = 2131099666;
			
			// aapt resource value: 0x7F060013
			public const int btnE = 2131099667;
			
			// aapt resource value: 0x7F060014
			public const int btnF = 2131099668;
			
			// aapt resource value: 0x7F060015
			public const int btnG = 2131099669;
			
			// aapt resource value: 0x7F060016
			public const int btnH = 2131099670;
			
			// aapt resource value: 0x7F060017
			public const int btnHighScores = 2131099671;
			
			// aapt resource value: 0x7F060018
			public const int btnI = 2131099672;
			
			// aapt resource value: 0x7F060019
			public const int btnJ = 2131099673;
			
			// aapt resource value: 0x7F06001A
			public const int btnK = 2131099674;
			
			// aapt resource value: 0x7F06001B
			public const int btnL = 2131099675;
			
			// aapt resource value: 0x7F06001C
			public const int btnM = 2131099676;
			
			// aapt resource value: 0x7F06001D
			public const int btnMenu = 2131099677;
			
			// aapt resource value: 0x7F06001E
			public const int btnN = 2131099678;
			
			// aapt resource value: 0x7F06001F
			public const int btnNewGame = 2131099679;
			
			// aapt resource value: 0x7F060020
			public const int btnO = 2131099680;
			
			// aapt resource value: 0x7F060021
			public const int btnP = 2131099681;
			
			// aapt resource value: 0x7F060022
			public const int btnPlay = 2131099682;
			
			// aapt resource value: 0x7F060023
			public const int btnPlayHangman = 2131099683;
			
			// aapt resource value: 0x7F060024
			public const int btnQ = 2131099684;
			
			// aapt resource value: 0x7F060025
			public const int btnR = 2131099685;
			
			// aapt resource value: 0x7F060026
			public const int btnS = 2131099686;
			
			// aapt resource value: 0x7F060027
			public const int btnStart = 2131099687;
			
			// aapt resource value: 0x7F060028
			public const int btnT = 2131099688;
			
			// aapt resource value: 0x7F060029
			public const int btnU = 2131099689;
			
			// aapt resource value: 0x7F06002A
			public const int btnV = 2131099690;
			
			// aapt resource value: 0x7F06002B
			public const int btnW = 2131099691;
			
			// aapt resource value: 0x7F06002C
			public const int btnX = 2131099692;
			
			// aapt resource value: 0x7F06002D
			public const int btnY = 2131099693;
			
			// aapt resource value: 0x7F06002E
			public const int btnZ = 2131099694;
			
			// aapt resource value: 0x7F06002F
			public const int button5 = 2131099695;
			
			// aapt resource value: 0x7F060030
			public const int button6 = 2131099696;
			
			// aapt resource value: 0x7F060031
			public const int button7 = 2131099697;
			
			// aapt resource value: 0x7F060032
			public const int button8 = 2131099698;
			
			// aapt resource value: 0x7F060033
			public const int center = 2131099699;
			
			// aapt resource value: 0x7F060034
			public const int center_horizontal = 2131099700;
			
			// aapt resource value: 0x7F060035
			public const int center_vertical = 2131099701;
			
			// aapt resource value: 0x7F060036
			public const int chronometer = 2131099702;
			
			// aapt resource value: 0x7F060037
			public const int clip_horizontal = 2131099703;
			
			// aapt resource value: 0x7F060038
			public const int clip_vertical = 2131099704;
			
			// aapt resource value: 0x7F060039
			public const int end = 2131099705;
			
			// aapt resource value: 0x7F06003A
			public const int fill = 2131099706;
			
			// aapt resource value: 0x7F06003B
			public const int fill_horizontal = 2131099707;
			
			// aapt resource value: 0x7F06003C
			public const int fill_vertical = 2131099708;
			
			// aapt resource value: 0x7F06003D
			public const int forever = 2131099709;
			
			// aapt resource value: 0x7F06003E
			public const int icon = 2131099710;
			
			// aapt resource value: 0x7F06003F
			public const int icon_group = 2131099711;
			
			// aapt resource value: 0x7F060040
			public const int imageView = 2131099712;
			
			// aapt resource value: 0x7F060041
			public const int imageView1 = 2131099713;
			
			// aapt resource value: 0x7F060042
			public const int info = 2131099714;
			
			// aapt resource value: 0x7F060043
			public const int italic = 2131099715;
			
			// aapt resource value: 0x7F060044
			public const int lbldescription = 2131099716;
			
			// aapt resource value: 0x7F060045
			public const int lbltitle = 2131099717;
			
			// aapt resource value: 0x7F060046
			public const int left = 2131099718;
			
			// aapt resource value: 0x7F060047
			public const int line1 = 2131099719;
			
			// aapt resource value: 0x7F060048
			public const int line3 = 2131099720;
			
			// aapt resource value: 0x7F060049
			public const int linearLayout1 = 2131099721;
			
			// aapt resource value: 0x7F06004A
			public const int linearLayout2 = 2131099722;
			
			// aapt resource value: 0x7F06004B
			public const int linearLayout3 = 2131099723;
			
			// aapt resource value: 0x7F06004C
			public const int linearLayout4 = 2131099724;
			
			// aapt resource value: 0x7F06004D
			public const int linearLayout5 = 2131099725;
			
			// aapt resource value: 0x7F06004E
			public const int linearLayout7 = 2131099726;
			
			// aapt resource value: 0x7F06004F
			public const int none = 2131099727;
			
			// aapt resource value: 0x7F060050
			public const int normal = 2131099728;
			
			// aapt resource value: 0x7F060051
			public const int notification_background = 2131099729;
			
			// aapt resource value: 0x7F060052
			public const int notification_main_column = 2131099730;
			
			// aapt resource value: 0x7F060053
			public const int notification_main_column_container = 2131099731;
			
			// aapt resource value: 0x7F060054
			public const int relativeLayout1 = 2131099732;
			
			// aapt resource value: 0x7F060055
			public const int right = 2131099733;
			
			// aapt resource value: 0x7F060056
			public const int right_icon = 2131099734;
			
			// aapt resource value: 0x7F060057
			public const int right_side = 2131099735;
			
			// aapt resource value: 0x7F060000
			public const int SPDifficulty = 2131099648;
			
			// aapt resource value: 0x7F060058
			public const int sqlite_id = 2131099736;
			
			// aapt resource value: 0x7F060059
			public const int start = 2131099737;
			
			// aapt resource value: 0x7F06005A
			public const int tag_transition_group = 2131099738;
			
			// aapt resource value: 0x7F06005B
			public const int tag_unhandled_key_event_manager = 2131099739;
			
			// aapt resource value: 0x7F06005C
			public const int tag_unhandled_key_listeners = 2131099740;
			
			// aapt resource value: 0x7F06005D
			public const int text = 2131099741;
			
			// aapt resource value: 0x7F06005E
			public const int text2 = 2131099742;
			
			// aapt resource value: 0x7F060060
			public const int textView1 = 2131099744;
			
			// aapt resource value: 0x7F06005F
			public const int textVWord = 2131099743;
			
			// aapt resource value: 0x7F060061
			public const int time = 2131099745;
			
			// aapt resource value: 0x7F060062
			public const int title = 2131099746;
			
			// aapt resource value: 0x7F060063
			public const int top = 2131099747;
			
			// aapt resource value: 0x7F060064
			public const int txtName = 2131099748;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7F070000
			public const int status_bar_notification_info_maxnum = 2131165184;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F080000
			public const int browser_actions_context_menu_page = 2131230720;
			
			// aapt resource value: 0x7F080001
			public const int browser_actions_context_menu_row = 2131230721;
			
			// aapt resource value: 0x7F080002
			public const int HighScores = 2131230722;
			
			// aapt resource value: 0x7F080003
			public const int Main = 2131230723;
			
			// aapt resource value: 0x7F080004
			public const int Menu = 2131230724;
			
			// aapt resource value: 0x7F080005
			public const int Name = 2131230725;
			
			// aapt resource value: 0x7F080006
			public const int notification_action = 2131230726;
			
			// aapt resource value: 0x7F080007
			public const int notification_action_tombstone = 2131230727;
			
			// aapt resource value: 0x7F080008
			public const int notification_template_custom_big = 2131230728;
			
			// aapt resource value: 0x7F080009
			public const int notification_template_icon_group = 2131230729;
			
			// aapt resource value: 0x7F08000A
			public const int notification_template_part_chronometer = 2131230730;
			
			// aapt resource value: 0x7F08000B
			public const int notification_template_part_time = 2131230731;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F090000
			public const int ApplicationName = 2131296256;
			
			// aapt resource value: 0x7F090001
			public const int difficulty_prompt = 2131296257;
			
			// aapt resource value: 0x7F090002
			public const int status_bar_notification_info_overflow = 2131296258;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F0A0000
			public const int TextAppearance_Compat_Notification = 2131361792;
			
			// aapt resource value: 0x7F0A0001
			public const int TextAppearance_Compat_Notification_Info = 2131361793;
			
			// aapt resource value: 0x7F0A0002
			public const int TextAppearance_Compat_Notification_Line2 = 2131361794;
			
			// aapt resource value: 0x7F0A0003
			public const int TextAppearance_Compat_Notification_Time = 2131361795;
			
			// aapt resource value: 0x7F0A0004
			public const int TextAppearance_Compat_Notification_Title = 2131361796;
			
			// aapt resource value: 0x7F0A0005
			public const int Widget_Compat_NotificationActionContainer = 2131361797;
			
			// aapt resource value: 0x7F0A0006
			public const int Widget_Compat_NotificationActionText = 2131361798;
			
			// aapt resource value: 0x7F0A0007
			public const int Widget_Support_CoordinatorLayout = 2131361799;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			// aapt resource value: { 0x10101A5,0x101031F,0x7F020000 }
			public static int[] ColorStateListItem = new int[] {
					16843173,
					16843551,
					2130837504};
			
			// aapt resource value: 2
			public const int ColorStateListItem_alpha = 2;
			
			// aapt resource value: 1
			public const int ColorStateListItem_android_alpha = 1;
			
			// aapt resource value: 0
			public const int ColorStateListItem_android_color = 0;
			
			// aapt resource value: { 0x7F02000C,0x7F020013 }
			public static int[] CoordinatorLayout = new int[] {
					2130837516,
					2130837523};
			
			// aapt resource value: 0
			public const int CoordinatorLayout_keylines = 0;
			
			// aapt resource value: { 0x10100B3,0x7F02000D,0x7F02000E,0x7F02000F,0x7F020010,0x7F020011,0x7F020012 }
			public static int[] CoordinatorLayout_Layout = new int[] {
					16842931,
					2130837517,
					2130837518,
					2130837519,
					2130837520,
					2130837521,
					2130837522};
			
			// aapt resource value: 0
			public const int CoordinatorLayout_Layout_android_layout_gravity = 0;
			
			// aapt resource value: 1
			public const int CoordinatorLayout_Layout_layout_anchor = 1;
			
			// aapt resource value: 2
			public const int CoordinatorLayout_Layout_layout_anchorGravity = 2;
			
			// aapt resource value: 3
			public const int CoordinatorLayout_Layout_layout_behavior = 3;
			
			// aapt resource value: 4
			public const int CoordinatorLayout_Layout_layout_dodgeInsetEdges = 4;
			
			// aapt resource value: 5
			public const int CoordinatorLayout_Layout_layout_insetEdge = 5;
			
			// aapt resource value: 6
			public const int CoordinatorLayout_Layout_layout_keyline = 6;
			
			// aapt resource value: 1
			public const int CoordinatorLayout_statusBarBackground = 1;
			
			// aapt resource value: { 0x7F020003,0x7F020004,0x7F020005,0x7F020006,0x7F020007,0x7F020008 }
			public static int[] FontFamily = new int[] {
					2130837507,
					2130837508,
					2130837509,
					2130837510,
					2130837511,
					2130837512};
			
			// aapt resource value: { 0x1010532,0x1010533,0x101053F,0x101056F,0x1010570,0x7F020002,0x7F020009,0x7F02000A,0x7F02000B,0x7F020014 }
			public static int[] FontFamilyFont = new int[] {
					16844082,
					16844083,
					16844095,
					16844143,
					16844144,
					2130837506,
					2130837513,
					2130837514,
					2130837515,
					2130837524};
			
			// aapt resource value: 0
			public const int FontFamilyFont_android_font = 0;
			
			// aapt resource value: 2
			public const int FontFamilyFont_android_fontStyle = 2;
			
			// aapt resource value: 4
			public const int FontFamilyFont_android_fontVariationSettings = 4;
			
			// aapt resource value: 1
			public const int FontFamilyFont_android_fontWeight = 1;
			
			// aapt resource value: 3
			public const int FontFamilyFont_android_ttcIndex = 3;
			
			// aapt resource value: 5
			public const int FontFamilyFont_font = 5;
			
			// aapt resource value: 6
			public const int FontFamilyFont_fontStyle = 6;
			
			// aapt resource value: 7
			public const int FontFamilyFont_fontVariationSettings = 7;
			
			// aapt resource value: 8
			public const int FontFamilyFont_fontWeight = 8;
			
			// aapt resource value: 9
			public const int FontFamilyFont_ttcIndex = 9;
			
			// aapt resource value: 0
			public const int FontFamily_fontProviderAuthority = 0;
			
			// aapt resource value: 1
			public const int FontFamily_fontProviderCerts = 1;
			
			// aapt resource value: 2
			public const int FontFamily_fontProviderFetchStrategy = 2;
			
			// aapt resource value: 3
			public const int FontFamily_fontProviderFetchTimeout = 3;
			
			// aapt resource value: 4
			public const int FontFamily_fontProviderPackage = 4;
			
			// aapt resource value: 5
			public const int FontFamily_fontProviderQuery = 5;
			
			// aapt resource value: { 0x101019D,0x101019E,0x10101A1,0x10101A2,0x10101A3,0x10101A4,0x1010201,0x101020B,0x1010510,0x1010511,0x1010512,0x1010513 }
			public static int[] GradientColor = new int[] {
					16843165,
					16843166,
					16843169,
					16843170,
					16843171,
					16843172,
					16843265,
					16843275,
					16844048,
					16844049,
					16844050,
					16844051};
			
			// aapt resource value: { 0x10101A5,0x1010514 }
			public static int[] GradientColorItem = new int[] {
					16843173,
					16844052};
			
			// aapt resource value: 0
			public const int GradientColorItem_android_color = 0;
			
			// aapt resource value: 1
			public const int GradientColorItem_android_offset = 1;
			
			// aapt resource value: 7
			public const int GradientColor_android_centerColor = 7;
			
			// aapt resource value: 3
			public const int GradientColor_android_centerX = 3;
			
			// aapt resource value: 4
			public const int GradientColor_android_centerY = 4;
			
			// aapt resource value: 1
			public const int GradientColor_android_endColor = 1;
			
			// aapt resource value: 10
			public const int GradientColor_android_endX = 10;
			
			// aapt resource value: 11
			public const int GradientColor_android_endY = 11;
			
			// aapt resource value: 5
			public const int GradientColor_android_gradientRadius = 5;
			
			// aapt resource value: 0
			public const int GradientColor_android_startColor = 0;
			
			// aapt resource value: 8
			public const int GradientColor_android_startX = 8;
			
			// aapt resource value: 9
			public const int GradientColor_android_startY = 9;
			
			// aapt resource value: 6
			public const int GradientColor_android_tileMode = 6;
			
			// aapt resource value: 2
			public const int GradientColor_android_type = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7F0C0000
			public const int xamarin_essentials_fileprovider_file_paths = 2131492864;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
